import 'package:flutter/material.dart';
import '../../core/api/bck_api_client.dart';
import '../../core/auth/session_store.dart';
import '../../core/theme/theme_controller.dart';
import '../agenda/agenda_page.dart';
import '../clients/clients_page.dart';
import '../devices/devices_page.dart';
import '../settings/settings_page.dart';
import '../users/users_page.dart';
class HomeShell extends StatefulWidget{const HomeShell({super.key,required this.session,required this.offline,required this.apiClient,required this.themeController});final StoredSession session;final bool offline;final BckApiClient apiClient;final ThemeController themeController;@override State<HomeShell>createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int _index=0;@override Widget build(BuildContext context){final pages=<Widget>[_HomePage(session:widget.session,offline:widget.offline,openAgenda:()=>setState(()=>_index=1)),AgendaPage(session:widget.session,apiClient:widget.apiClient),ClientsPage(session:widget.session),const _PlaceholderPage(icon:Icons.account_balance_wallet_rounded,title:'Financeiro'),_MorePage(session:widget.session,apiClient:widget.apiClient,themeController:widget.themeController)];return Scaffold(body:IndexedStack(index:_index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:_index,onDestinationSelected:(v)=>setState(()=>_index=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Início'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),selectedIcon:Icon(Icons.calendar_month_rounded),label:'Agenda'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people_rounded),label:'Clientes'),NavigationDestination(icon:Icon(Icons.account_balance_wallet_outlined),selectedIcon:Icon(Icons.account_balance_wallet_rounded),label:'Financeiro'),NavigationDestination(icon:Icon(Icons.grid_view_outlined),selectedIcon:Icon(Icons.grid_view_rounded),label:'Mais')]),floatingActionButton:FloatingActionButton(onPressed:()=>_quick(context),child:const Icon(Icons.add_rounded)));}void _quick(BuildContext context){showModalBottomSheet<void>(context:context,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Ação rápida',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:12),ListTile(leading:const Icon(Icons.event_available_rounded),title:const Text('Novo agendamento'),onTap:(){Navigator.pop(context);setState(()=>_index=1);}),ListTile(leading:const Icon(Icons.person_add_alt_1_rounded),title:const Text('Novo cliente'),onTap:(){Navigator.pop(context);setState(()=>_index=2);}),ListTile(leading:const Icon(Icons.point_of_sale_rounded),title:const Text('Nova venda'),onTap:()=>Navigator.pop(context)),ListTile(leading:const Icon(Icons.add_card_rounded),title:const Text('Novo lançamento'),onTap:()=>Navigator.pop(context))]))));}}
class _MorePage extends StatelessWidget{const _MorePage({required this.session,required this.apiClient,required this.themeController});final StoredSession session;final BckApiClient apiClient;final ThemeController themeController;@override Widget build(BuildContext context){final admin=session.profile=='ADMIN';return SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text('Mais',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:16),const ListTile(leading:Icon(Icons.inventory_2_outlined),title:Text('Produtos e serviços')),const ListTile(leading:Icon(Icons.warehouse_outlined),title:Text('Estoque')),if(admin)...[ListTile(leading:const Icon(Icons.manage_accounts_outlined),title:const Text('Usuários'),subtitle:const Text('Equipe, perfis e permissões'),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>UsersPage(apiClient:apiClient)))),ListTile(leading:const Icon(Icons.devices_other_rounded),title:const Text('Dispositivos'),subtitle:const Text('Conectar e administrar aparelhos'),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>DevicesPage(apiClient:apiClient))))],const ListTile(leading:Icon(Icons.assessment_outlined),title:Text('Relatórios')),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Configurações'),subtitle:const Text('Aparência e preferências deste aparelho'),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>SettingsPage(themeController:themeController))))]));}}
class _HomePage extends StatelessWidget{const _HomePage({required this.session,required this.offline,required this.openAgenda});final StoredSession session;final bool offline;final VoidCallback openAgenda;@override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,20,20,100),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('BCK Agenda',style:TextStyle(color:Theme.of(context).colorScheme.primary,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text('Olá, ${session.name}',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none_rounded))]),const SizedBox(height:16),_StatusBanner(offline:offline),const SizedBox(height:24),const Text('Atendimento atual',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700)),const SizedBox(height:10),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[CircleAvatar(child:Icon(Icons.person_outline)),SizedBox(width:12),Expanded(child:Text('Nenhum atendimento em andamento',style:TextStyle(fontWeight:FontWeight.w600)))]),const SizedBox(height:14),const Text('Quando um atendimento for iniciado, o cliente, cronômetro e ações aparecerão aqui.'),const SizedBox(height:14),FilledButton.icon(onPressed:openAgenda,icon:const Icon(Icons.play_arrow_rounded),label:const Text('Abrir agenda'))]))),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Próximos clientes',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700)),TextButton(onPressed:openAgenda,child:const Text('Ver agenda'))]),const _EmptyScheduleCard(),const _EmptyScheduleCard(),const _EmptyScheduleCard()]));}
class _StatusBanner extends StatelessWidget{const _StatusBanner({required this.offline});final bool offline;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(borderRadius:BorderRadius.circular(14),color:Theme.of(context).colorScheme.surfaceContainerHighest),child:Row(children:[Icon(offline?Icons.cloud_off_rounded:Icons.cloud_done_rounded,color:Theme.of(context).colorScheme.primary),const SizedBox(width:10),Expanded(child:Text(offline?'Modo offline • alterações serão sincronizadas depois':'Sincronizado • sessão validada'))]));}
class _EmptyScheduleCard extends StatelessWidget{const _EmptyScheduleCard();@override Widget build(BuildContext context)=>const Card(child:ListTile(leading:Icon(Icons.schedule_rounded),title:Text('Horário disponível'),subtitle:Text('Nenhum cliente agendado')));}
class _PlaceholderPage extends StatelessWidget{const _PlaceholderPage({required this.icon,required this.title});final IconData icon;final String title;@override Widget build(BuildContext context)=>SafeArea(child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:56,color:Theme.of(context).colorScheme.primary),const SizedBox(height:16),Text(title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Módulo preparado para a próxima etapa.',style:TextStyle(color:Colors.white60))])));}
