using System.Security.Cryptography;
using System.Text;
using Npgsql;

namespace Bck.Api.Features.Auth;

public sealed class AuthService(IConfiguration configuration, JwtTokenService jwtTokens)
{
    private static readonly TimeSpan RefreshTokenLifetime=TimeSpan.FromDays(30); private static readonly TimeSpan OfflineLeaseLifetime=TimeSpan.FromHours(24);
    public async Task<LoginResponse?> LoginAsync(LoginRequest request,CancellationToken ct){
        if(request.GroupId==Guid.Empty||request.DeviceId==Guid.Empty||string.IsNullOrWhiteSpace(request.Username)||string.IsNullOrEmpty(request.Password))return null;
        await using var c=new NpgsqlConnection(GetConnectionString());await c.OpenAsync(ct);
        Guid uid;string name,profile,hash,status,deviceMode;bool owner,must;DateTimeOffset? revoked;int pv,sv;bool linked;
        await using(var cmd=new NpgsqlCommand("SELECT u.id,u.name,u.profile,u.is_owner,u.must_change_password,u.password_hash,d.status,d.revoked_at,u.permission_version,d.security_version,d.device_mode,EXISTS(SELECT 1 FROM device_user du WHERE du.device_id=d.id AND du.user_id=u.id) FROM bck_user u JOIN device d ON d.group_id=u.group_id WHERE u.group_id=@g AND lower(u.username)=lower(@n) AND u.active=true AND d.id=@d LIMIT 1",c)){
            cmd.Parameters.AddWithValue("g",request.GroupId);cmd.Parameters.AddWithValue("n",request.Username.Trim());cmd.Parameters.AddWithValue("d",request.DeviceId);
            await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;
            uid=r.GetGuid(0);name=r.GetString(1);profile=r.GetString(2);owner=r.GetBoolean(3);must=r.GetBoolean(4);hash=r.GetString(5);status=r.GetString(6);revoked=r.IsDBNull(7)?null:r.GetFieldValue<DateTimeOffset>(7);pv=r.GetInt32(8);sv=r.GetInt32(9);deviceMode=r.GetString(10);linked=r.GetBoolean(11);
        }
        if(!status.Equals("ACTIVE",StringComparison.OrdinalIgnoreCase)||revoked is not null||!PasswordHasher.Verify(request.Password,hash))return null;
        var shared=deviceMode.Equals("SHARED",StringComparison.OrdinalIgnoreCase);
        if(!shared&&!linked)return null;
        var now=DateTimeOffset.UtcNow;var refresh=CreateOpaqueToken(48);var re=now.Add(RefreshTokenLifetime);var lease=now.Add(OfflineLeaseLifetime);var access=jwtTokens.Create(new(request.GroupId,uid,request.DeviceId,profile,owner,pv,sv),now,out var ae);
        await using var tx=await c.BeginTransactionAsync(ct);
        if(shared&&!linked){await using var link=new NpgsqlCommand("INSERT INTO device_user(device_id,user_id,last_login_at) VALUES(@d,@u,@n) ON CONFLICT(device_id,user_id) DO UPDATE SET last_login_at=EXCLUDED.last_login_at",c,tx);link.Parameters.AddWithValue("d",request.DeviceId);link.Parameters.AddWithValue("u",uid);link.Parameters.AddWithValue("n",now);await link.ExecuteNonQueryAsync(ct);}
        await InsertRefreshTokenAsync(c,tx,request.GroupId,uid,request.DeviceId,HashToken(refresh),re,now,null,ct);
        await using(var up=new NpgsqlCommand("UPDATE bck_user SET last_login_at=@n,updated_at=@n WHERE id=@u; UPDATE device SET last_validated_at=@n,updated_at=@n WHERE id=@d; UPDATE device_user SET last_login_at=@n WHERE device_id=@d AND user_id=@u;",c,tx)){up.Parameters.AddWithValue("n",now);up.Parameters.AddWithValue("u",uid);up.Parameters.AddWithValue("d",request.DeviceId);await up.ExecuteNonQueryAsync(ct);}
        await tx.CommitAsync(ct);return new(request.GroupId,uid,request.DeviceId,name,profile,owner,must,access,ae,refresh,re,lease,now,now);
    }
    public async Task<RefreshResponse?> RefreshAsync(RefreshRequest request,CancellationToken ct){if(string.IsNullOrWhiteSpace(request.RefreshToken))return null;var oldHash=HashToken(request.RefreshToken);await using var c=new NpgsqlConnection(GetConnectionString());await c.OpenAsync(ct);Guid oldId,g,u,d;string profile;bool owner;int pv,sv;await using(var s=new NpgsqlCommand("SELECT rt.id,rt.group_id,rt.user_id,rt.device_id,u.profile,u.is_owner,u.permission_version,d.security_version FROM refresh_token rt JOIN bck_user u ON u.id=rt.user_id AND u.active=true JOIN device d ON d.id=rt.device_id AND d.status='ACTIVE' AND d.revoked_at IS NULL WHERE rt.token_hash=@h AND rt.revoked_at IS NULL AND rt.expires_at>now() LIMIT 1",c)){s.Parameters.AddWithValue("h",oldHash);await using var r=await s.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;oldId=r.GetGuid(0);g=r.GetGuid(1);u=r.GetGuid(2);d=r.GetGuid(3);profile=r.GetString(4);owner=r.GetBoolean(5);pv=r.GetInt32(6);sv=r.GetInt32(7);}var now=DateTimeOffset.UtcNow;var refresh=CreateOpaqueToken(48);var re=now.Add(RefreshTokenLifetime);var lease=now.Add(OfflineLeaseLifetime);var access=jwtTokens.Create(new(g,u,d,profile,owner,pv,sv),now,out var ae);var newId=Guid.NewGuid();await using var tx=await c.BeginTransactionAsync(ct);await InsertRefreshTokenAsync(c,tx,g,u,d,HashToken(refresh),re,now,newId,ct);await using(var rv=new NpgsqlCommand("UPDATE refresh_token SET revoked_at=@n,replaced_by_token_id=@new,last_used_at=@n WHERE id=@old AND revoked_at IS NULL",c,tx)){rv.Parameters.AddWithValue("n",now);rv.Parameters.AddWithValue("new",newId);rv.Parameters.AddWithValue("old",oldId);if(await rv.ExecuteNonQueryAsync(ct)!=1){await tx.RollbackAsync(ct);return null;}}await using(var dv=new NpgsqlCommand("UPDATE device SET last_validated_at=@n,updated_at=@n WHERE id=@d",c,tx)){dv.Parameters.AddWithValue("n",now);dv.Parameters.AddWithValue("d",d);await dv.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return new(access,ae,refresh,re,lease,now,now);}
    public async Task LogoutAsync(LogoutRequest request,CancellationToken ct){if(string.IsNullOrWhiteSpace(request.RefreshToken))return;await using var c=new NpgsqlConnection(GetConnectionString());await c.OpenAsync(ct);await using var cmd=new NpgsqlCommand("UPDATE refresh_token SET revoked_at=COALESCE(revoked_at,now()) WHERE token_hash=@h",c);cmd.Parameters.AddWithValue("h",HashToken(request.RefreshToken));await cmd.ExecuteNonQueryAsync(ct);}
    private string GetConnectionString()=>configuration.GetConnectionString("Postgres")??Environment.GetEnvironmentVariable("BCK_POSTGRES_CONNECTION")??throw new InvalidOperationException("PostgreSQL connection is not configured.");
    private static async Task InsertRefreshTokenAsync(NpgsqlConnection c,NpgsqlTransaction tx,Guid g,Guid u,Guid d,string hash,DateTimeOffset expires,DateTimeOffset now,Guid? id,CancellationToken ct){await using var cmd=new NpgsqlCommand("INSERT INTO refresh_token(id,group_id,user_id,device_id,token_hash,expires_at,last_used_at) VALUES(@id,@g,@u,@d,@h,@e,@n)",c,tx);cmd.Parameters.AddWithValue("id",id??Guid.NewGuid());cmd.Parameters.AddWithValue("g",g);cmd.Parameters.AddWithValue("u",u);cmd.Parameters.AddWithValue("d",d);cmd.Parameters.AddWithValue("h",hash);cmd.Parameters.AddWithValue("e",expires);cmd.Parameters.AddWithValue("n",now);await cmd.ExecuteNonQueryAsync(ct);}
    private static string CreateOpaqueToken(int bytes)=>Convert.ToBase64String(RandomNumberGenerator.GetBytes(bytes)); private static string HashToken(string token)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));
}
