using Npgsql;
namespace Bck.Api.Features.Auth;
public sealed record UserListItem(Guid Id,string Name,string? Phone,string? FunctionName,string Profile,bool IsOwner,bool ServesClients,bool Active,int PermissionVersion,IReadOnlyList<string> Permissions);
public sealed record CreateManagedUserRequest(string Name,string? Phone,string? FunctionName,string Profile,bool ServesClients,string Username,string Password,IReadOnlyList<string>? Permissions);
public sealed record UpdateManagedUserRequest(string Name,string? Phone,string? FunctionName,string Profile,bool ServesClients,bool Active,IReadOnlyList<string>? Permissions);
public sealed record ResetUserPasswordRequest(string Password);
public sealed class UserManagementService(IConfiguration configuration){
public async Task<IReadOnlyList<UserListItem>>ListAsync(Guid groupId,CancellationToken ct){var list=new List<UserListItem>();await using var c=new NpgsqlConnection(Cs());await c.OpenAsync(ct);await using var q=new NpgsqlCommand("SELECT u.id,u.name,u.phone,u.function_name,u.profile,u.is_owner,u.serves_clients,u.active,u.permission_version,coalesce(array_agg(p.code) filter(where up.granted=true and p.code is not null),'{}') FROM bck_user u LEFT JOIN user_permission up ON up.user_id=u.id LEFT JOIN permission p ON p.id=up.permission_id WHERE u.group_id=$1 GROUP BY u.id ORDER BY u.is_owner DESC,u.active DESC,u.name",c);q.Parameters.AddWithValue(groupId);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetString(4),r.GetBoolean(5),r.GetBoolean(6),r.GetBoolean(7),r.GetInt32(8),r.GetFieldValue<string[]>(9)));return list;}
public async Task<Guid>CreateAsync(Guid groupId,Guid actor,CreateManagedUserRequest r,CancellationToken ct){Validate(r.Name,r.Profile,r.Username,r.Password);await using var c=new NpgsqlConnection(Cs());await c.OpenAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var id=Guid.NewGuid();await using(var q=new NpgsqlCommand("INSERT INTO bck_user(id,group_id,name,phone,function_name,profile,serves_clients,password_hash,username) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",c,t)){q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(groupId);q.Parameters.AddWithValue(r.Name.Trim());q.Parameters.AddWithValue((object?)r.Phone??DBNull.Value);q.Parameters.AddWithValue((object?)r.FunctionName??DBNull.Value);q.Parameters.AddWithValue(r.Profile.Trim().ToUpperInvariant());q.Parameters.AddWithValue(r.ServesClients);q.Parameters.AddWithValue(PasswordHasher.Hash(r.Password));q.Parameters.AddWithValue(r.Username.Trim());await q.ExecuteNonQueryAsync(ct);}await SetPermissions(c,t,id,r.Permissions,ct);await Audit(c,t,groupId,actor,id,"USER_CREATED",ct);await t.CommitAsync(ct);return id;}
public async Task<bool>UpdateAsync(Guid groupId,Guid actor,Guid id,UpdateManagedUserRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.Profile.Trim().ToUpperInvariant() is not("ADMIN" or "USER"))throw new ArgumentException("Dados do usuário inválidos.");await using var c=new NpgsqlConnection(Cs());await c.OpenAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("UPDATE bck_user SET name=$3,phone=$4,function_name=$5,profile=CASE WHEN is_owner THEN 'ADMIN' ELSE $6 END,serves_clients=$7,active=CASE WHEN is_owner THEN true ELSE $8 END,permission_version=permission_version+1,version=version+1,updated_at=now() WHERE id=$1 AND group_id=$2",c,t);q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(groupId);q.Parameters.AddWithValue(r.Name.Trim());q.Parameters.AddWithValue((object?)r.Phone??DBNull.Value);q.Parameters.AddWithValue((object?)r.FunctionName??DBNull.Value);q.Parameters.AddWithValue(r.Profile.Trim().ToUpperInvariant());q.Parameters.AddWithValue(r.ServesClients);q.Parameters.AddWithValue(r.Active);if(await q.ExecuteNonQueryAsync(ct)!=1){await t.RollbackAsync(ct);return false;}await SetPermissions(c,t,id,r.Permissions,ct);await Audit(c,t,groupId,actor,id,"USER_UPDATED",ct);await t.CommitAsync(ct);return true;}
public async Task<bool>ResetPasswordAsync(Guid groupId,Guid actor,Guid id,string password,CancellationToken ct){if(password.Length<8)throw new ArgumentException("A senha deve ter pelo menos 8 caracteres.");await using var c=new NpgsqlConnection(Cs());await c.OpenAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("UPDATE bck_user SET password_hash=$3,permission_version=permission_version+1,version=version+1,updated_at=now() WHERE id=$1 AND group_id=$2",c,t);q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(groupId);q.Parameters.AddWithValue(PasswordHasher.Hash(password));if(await q.ExecuteNonQueryAsync(ct)!=1){await t.RollbackAsync(ct);return false;}await Audit(c,t,groupId,actor,id,"USER_PASSWORD_RESET",ct);await t.CommitAsync(ct);return true;}
static void Validate(string name,string profile,string username,string password){if(string.IsNullOrWhiteSpace(name)||string.IsNullOrWhiteSpace(username)||password.Length<8||profile.Trim().ToUpperInvariant() is not("ADMIN" or "USER"))throw new ArgumentException("Dados do usuário inválidos.");}
static async Task SetPermissions(NpgsqlConnection c,NpgsqlTransaction t,Guid id,IReadOnlyList<string>? codes,CancellationToken ct){await using(var d=new NpgsqlCommand("DELETE FROM user_permission WHERE user_id=$1",c,t)){d.Parameters.AddWithValue(id);await d.ExecuteNonQueryAsync(ct);}foreach(var code in(codes??[]).Distinct(StringComparer.OrdinalIgnoreCase)){await using var q=new NpgsqlCommand("INSERT INTO user_permission(user_id,permission_id,granted) SELECT $1,id,true FROM permission WHERE code=$2 ON CONFLICT(user_id,permission_id) DO UPDATE SET granted=true",c,t);q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(code.Trim().ToUpperInvariant());await q.ExecuteNonQueryAsync(ct);}}
static async Task Audit(NpgsqlConnection c,NpgsqlTransaction t,Guid g,Guid a,Guid id,string action,CancellationToken ct){await using var q=new NpgsqlCommand("INSERT INTO audit_log(group_id,user_id,action,entity_type,entity_id) VALUES($1,$2,$3,'USER',$4)",c,t);q.Parameters.AddWithValue(g);q.Parameters.AddWithValue(a);q.Parameters.AddWithValue(action);q.Parameters.AddWithValue(id);await q.ExecuteNonQueryAsync(ct);}
string Cs()=>configuration.GetConnectionString("Postgres")??Environment.GetEnvironmentVariable("BCK_POSTGRES_CONNECTION")??throw new InvalidOperationException("PostgreSQL connection is not configured.");}
