import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../api/bck_api_client.dart';
class StoredSession{const StoredSession({required this.groupId,required this.userId,required this.deviceId,required this.name,required this.profile,required this.isOwner,required this.accessToken,required this.accessTokenExpiresAt,required this.refreshToken,required this.refreshTokenExpiresAt,required this.offlineLeaseExpiresAt,required this.serverTimeUtc,required this.validatedAt,required this.localValidatedAt});final String groupId,userId,deviceId,name,profile,accessToken,refreshToken;final bool isOwner;final DateTime accessTokenExpiresAt,refreshTokenExpiresAt,offlineLeaseExpiresAt,serverTimeUtc,validatedAt,localValidatedAt;
  DateTime estimatedServerNow([DateTime? localNow]){final now=(localNow??DateTime.now()).toUtc();final elapsed=now.difference(localValidatedAt.toUtc());if(elapsed.isNegative)return offlineLeaseExpiresAt.toUtc();return serverTimeUtc.toUtc().add(elapsed);}
  bool canOperateOfflineAt([DateTime? localNow])=>estimatedServerNow(localNow).isBefore(offlineLeaseExpiresAt.toUtc()); bool get canOperateOffline=>canOperateOfflineAt();}
class SessionStore{SessionStore({FlutterSecureStorage?storage}):_storage=storage??const FlutterSecureStorage();final FlutterSecureStorage _storage;static const _groupId='auth.groupId',_userId='auth.userId',_deviceId='auth.deviceId',_name='auth.name',_profile='auth.profile',_isOwner='auth.isOwner',_accessToken='auth.accessToken',_accessExpires='auth.accessExpires',_refreshToken='auth.refreshToken',_refreshExpires='auth.refreshExpires',_offlineLeaseExpires='auth.offlineLeaseExpires',_serverTime='auth.serverTimeUtc',_validatedAt='auth.validatedAt',_localValidatedAt='auth.localValidatedAt';static const _authKeys=[_groupId,_userId,_deviceId,_name,_profile,_isOwner,_accessToken,_accessExpires,_refreshToken,_refreshExpires,_offlineLeaseExpires,_serverTime,_validatedAt,_localValidatedAt];
Future<void>save(AuthSession s)async{final local=DateTime.now().toUtc();await Future.wait([_storage.write(key:_groupId,value:s.groupId),_storage.write(key:_userId,value:s.userId),_storage.write(key:_deviceId,value:s.deviceId),_storage.write(key:_name,value:s.name),_storage.write(key:_profile,value:s.profile),_storage.write(key:_isOwner,value:s.isOwner.toString()),_storage.write(key:_accessToken,value:s.accessToken),_storage.write(key:_accessExpires,value:s.accessTokenExpiresAt.toUtc().toIso8601String()),_storage.write(key:_refreshToken,value:s.refreshToken),_storage.write(key:_refreshExpires,value:s.refreshTokenExpiresAt.toUtc().toIso8601String()),_storage.write(key:_offlineLeaseExpires,value:s.offlineLeaseExpiresAt.toUtc().toIso8601String()),_storage.write(key:_serverTime,value:s.serverTimeUtc.toUtc().toIso8601String()),_storage.write(key:_validatedAt,value:s.validatedAt.toUtc().toIso8601String()),_storage.write(key:_localValidatedAt,value:local.toIso8601String())]);}
Future<void>updateTokens({required String accessToken,required DateTime accessTokenExpiresAt,required String refreshToken,required DateTime refreshTokenExpiresAt,required DateTime offlineLeaseExpiresAt,required DateTime serverTimeUtc,required DateTime validatedAt})async{final local=DateTime.now().toUtc();await Future.wait([_storage.write(key:_accessToken,value:accessToken),_storage.write(key:_accessExpires,value:accessTokenExpiresAt.toUtc().toIso8601String()),_storage.write(key:_refreshToken,value:refreshToken),_storage.write(key:_refreshExpires,value:refreshTokenExpiresAt.toUtc().toIso8601String()),_storage.write(key:_offlineLeaseExpires,value:offlineLeaseExpiresAt.toUtc().toIso8601String()),_storage.write(key:_serverTime,value:serverTimeUtc.toUtc().toIso8601String()),_storage.write(key:_validatedAt,value:validatedAt.toUtc().toIso8601String()),_storage.write(key:_localValidatedAt,value:local.toIso8601String())]);}
Future<StoredSession?>read()async{final v=await Future.wait([_storage.read(key:_groupId),_storage.read(key:_userId),_storage.read(key:_deviceId),_storage.read(key:_name),_storage.read(key:_profile),_storage.read(key:_isOwner),_storage.read(key:_accessToken),_storage.read(key:_accessExpires),_storage.read(key:_refreshToken),_storage.read(key:_refreshExpires),_storage.read(key:_offlineLeaseExpires),_storage.read(key:_serverTime),_storage.read(key:_validatedAt),_storage.read(key:_localValidatedAt)]);if(v.any((x)=>x==null))return null;try{return StoredSession(groupId:v[0]!,userId:v[1]!,deviceId:v[2]!,name:v[3]!,profile:v[4]!,isOwner:v[5]=='true',accessToken:v[6]!,accessTokenExpiresAt:DateTime.parse(v[7]!),refreshToken:v[8]!,refreshTokenExpiresAt:DateTime.parse(v[9]!),offlineLeaseExpiresAt:DateTime.parse(v[10]!),serverTimeUtc:DateTime.parse(v[11]!),validatedAt:DateTime.parse(v[12]!),localValidatedAt:DateTime.parse(v[13]!));}on FormatException{await clear();return null;}}
Future<void>clear()async=>Future.wait(_authKeys.map((k)=>_storage.delete(key:k)));}
