import 'package:flutter/material.dart';
import '../../core/api/bck_api_client.dart';

class DevicesPage extends StatefulWidget{const DevicesPage({super.key,required this.apiClient});final BckApiClient apiClient;@override State<DevicesPage> createState()=>_DevicesPageState();}
class _DevicesPageState extends State<DevicesPage>{String _mode='PERSONAL';PairingCode?_pairing;List<DeviceItem>_devices=[];bool _loading=false,_loadingDevices=true;String?_error;
@override void initState(){super.initState();_loadDevices();}
Future<void>_loadDevices()async{setState(()=>_loadingDevices=true);try{final items=await widget.apiClient.devices();if(mounted)setState(()=>_devices=items);}catch(_){if(mounted)setState(()=>_error='Não foi possível carregar os aparelhos.');}finally{if(mounted)setState(()=>_loadingDevices=false);}}
Future<void>_generate()async{setState((){_loading=true;_error=null;});try{final p=await widget.apiClient.createPairingCode(_mode);if(mounted)setState(()=>_pairing=p);}catch(_){if(mounted)setState(()=>_error='Não foi possível gerar o código. Verifique a conexão e suas permissões.');}finally{if(mounted)setState(()=>_loading=false);}}
Future<void>_changeMode(DeviceItem d)async{final next=d.deviceMode=='PERSONAL'?'SHARED':'PERSONAL';final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Alterar tipo do aparelho?'),content:Text('Alterar ${d.name} para ${next=='SHARED'?'Compartilhado':'Pessoal'}? O acesso rápido deste aparelho será desativado e será necessário autenticar novamente.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Alterar'))]))??false;if(!ok)return;try{await widget.apiClient.changeDeviceMode(d.id,next);await _loadDevices();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Tipo do aparelho atualizado.')));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Não foi possível alterar o aparelho.')));}}
Future<void>_revoke(DeviceItem d)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Revogar aparelho?'),content:Text('${d.name} perderá o acesso à empresa assim que estiver online. Esta ação não exclui o histórico.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Revogar'))]))??false;if(!ok)return;try{await widget.apiClient.revokeDevice(d.id);await _loadDevices();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Aparelho revogado.')));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Não foi possível revogar o aparelho.')));}}
String _when(DateTime?d){if(d==null)return 'Nunca';final x=d.toLocal();return '${x.day.toString().padLeft(2,'0')}/${x.month.toString().padLeft(2,'0')}/${x.year} ${x.hour.toString().padLeft(2,'0')}:${x.minute.toString().padLeft(2,'0')}';}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Dispositivos'),actions:[IconButton(onPressed:_loadingDevices?null:_loadDevices,icon:const Icon(Icons.refresh),tooltip:'Atualizar')]),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Aparelhos autorizados',style:TextStyle(fontSize:22,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Gerencie os aparelhos conectados somente a esta empresa.'),const SizedBox(height:16),if(_loadingDevices)const Center(child:Padding(padding:EdgeInsets.all(20),child:CircularProgressIndicator()))else if(_devices.isEmpty)const Text('Nenhum aparelho autorizado.')else ..._devices.map((d)=>Card(child:ListTile(isThreeLine:true,leading:Icon(d.deviceMode=='SHARED'?Icons.groups_outlined:Icons.smartphone),title:Row(children:[Expanded(child:Text(d.name)),if(d.isPrincipal)const Chip(label:Text('Principal'))]),subtitle:Text('${d.deviceMode=='SHARED'?'Compartilhado':'Pessoal'} • ${d.status=='ACTIVE'?'Ativo':'Revogado'}\nÚltimo acesso: ${_when(d.lastLoginAt??d.lastValidatedAt)} • ${d.linkedUsers} usuário(s)'),trailing:PopupMenuButton<String>(enabled:d.status=='ACTIVE',onSelected:(v){if(v=='mode')_changeMode(d);if(v=='revoke')_revoke(d);},itemBuilder:(_)=>[PopupMenuItem(value:'mode',child:Text(d.deviceMode=='PERSONAL'?'Tornar compartilhado':'Tornar pessoal')),if(!d.isPrincipal)const PopupMenuItem(value:'revoke',child:Text('Revogar aparelho'))])))),const Divider(height:40),const Text('Conectar novo aparelho',style:TextStyle(fontSize:22,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Gere um código temporário para conectar outro aparelho somente a esta empresa.'),const SizedBox(height:24),SegmentedButton<String>(segments:const[ButtonSegment(value:'PERSONAL',label:Text('Pessoal'),icon:Icon(Icons.person_outline)),ButtonSegment(value:'SHARED',label:Text('Compartilhado'),icon:Icon(Icons.groups_outlined))],selected:{_mode},onSelectionChanged:(s)=>setState(()=>_mode=s.first)),const SizedBox(height:20),FilledButton.icon(onPressed:_loading?null:_generate,icon:const Icon(Icons.add_link_rounded),label:Text(_loading?'Gerando...':'Gerar código de conexão')),if(_error!=null)...[const SizedBox(height:16),Text(_error!,style:TextStyle(color:Theme.of(context).colorScheme.error))],if(_pairing!=null)...[const SizedBox(height:28),Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(children:[const Text('Código de conexão',style:TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:12),SelectableText(_pairing!.code,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800,letterSpacing:3)),const SizedBox(height:12),Text('Válido até ${TimeOfDay.fromDateTime(_pairing!.expiresAt.toLocal()).format(context)}'),const SizedBox(height:8),const Text('Use este código no novo aparelho em “Conectar a uma empresa existente”.',textAlign:TextAlign.center)])))] ]));}
