using System.Security.Claims;
using Bck.Api.Features.Agenda;
using Bck.Api.Features.Auth;
using Bck.Api.Features.Bootstrap;
using Bck.Api.Infrastructure.Database;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Npgsql;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks(); builder.Services.AddOpenApi(); builder.Services.AddSingleton<PostgresProbe>(); builder.Services.AddScoped<BootstrapService>(); builder.Services.AddSingleton<JwtTokenService>(); builder.Services.AddScoped<AuthService>(); builder.Services.AddScoped<AgendaService>();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => { options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer=true,ValidIssuer=JwtTokenService.Issuer,ValidateAudience=true,ValidAudience=JwtTokenService.Audience,ValidateIssuerSigningKey=true,IssuerSigningKey=new SymmetricSecurityKey(JwtTokenService.GetSigningKey(builder.Configuration)),ValidateLifetime=true,ClockSkew=TimeSpan.FromSeconds(30) }; }); builder.Services.AddAuthorization();
var app=builder.Build(); if(app.Environment.IsDevelopment())app.MapOpenApi(); app.UseAuthentication(); app.UseAuthorization();
app.MapGet("/api/v1/health",()=>Results.Ok(new{status="ok",service="BCK Agenda API",version="0.4.2",serverTimeUtc=DateTimeOffset.UtcNow}));
app.MapGet("/api/v1/health/database",async(PostgresProbe probe,CancellationToken ct)=>{var r=await probe.CheckAsync(ct);return r.Ready?Results.Ok(new{status="ok",database=r.Database,foundationMigration="applied"}):Results.Json(new{status="unavailable",code="DATABASE_UNAVAILABLE"},statusCode:503);}); app.MapGet("/api/v1/system/time",()=>Results.Ok(new{serverTimeUtc=DateTimeOffset.UtcNow}));
app.MapPost("/api/v1/bootstrap/company",async(CreateCompanyRequest request,BootstrapService service,CancellationToken ct)=>{try{var r=await service.CreateCompanyAsync(request,ct);return Results.Created($"/api/v1/groups/{r.GroupId}",r);}catch(ArgumentException ex){return Results.BadRequest(new{code="VALIDATION_ERROR",message=ex.Message});}});
app.MapPost("/api/v1/auth/login",async(LoginRequest request,AuthService service,CancellationToken ct)=>{var r=await service.LoginAsync(request,ct);return r is null?Results.Json(new{code="INVALID_CREDENTIALS",message="Credenciais ou dispositivo inválidos."},statusCode:401):Results.Ok(r);}); app.MapPost("/api/v1/auth/refresh",async(RefreshRequest request,AuthService service,CancellationToken ct)=>{var r=await service.RefreshAsync(request,ct);return r is null?Results.Json(new{code="INVALID_REFRESH_TOKEN",message="Sessão expirada, revogada ou inválida."},statusCode:401):Results.Ok(r);}); app.MapPost("/api/v1/auth/logout",async(LogoutRequest request,AuthService service,CancellationToken ct)=>{await service.LogoutAsync(request,ct);return Results.NoContent();});
app.MapGet("/api/v1/auth/me",(ClaimsPrincipal user)=>Results.Ok(new{userId=user.FindFirstValue(ClaimTypes.NameIdentifier)??user.FindFirstValue("sub"),groupId=user.FindFirstValue("group_id"),deviceId=user.FindFirstValue("device_id"),profile=user.FindFirstValue("profile"),isOwner=string.Equals(user.FindFirstValue("is_owner"),"true",StringComparison.OrdinalIgnoreCase),permissionVersion=user.FindFirstValue("permission_version"),securityVersion=user.FindFirstValue("security_version")})).RequireAuthorization();
var api=app.MapGroup("/api/v1").RequireAuthorization();
api.MapPost("/clients",async(CreateClientRequest request,ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>{try{var r=await service.CreateClientAsync(request with{GroupId=GroupId(user),CreatedByUserId=UserId(user)},ct);return Results.Created($"/api/v1/clients/{r.Id}",r);}catch(ArgumentException ex){return Results.BadRequest(new{code="VALIDATION_ERROR",message=ex.Message});}}); api.MapGet("/clients",async(string? q,ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>Results.Ok(await service.SearchClientsAsync(GroupId(user),q,ct)));
api.MapPost("/services",async(CreateServiceRequest request,ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>{if(!IsAdmin(user))return Results.Forbid();try{var r=await service.CreateServiceAsync(request with{GroupId=GroupId(user)},ct);return Results.Created($"/api/v1/services/{r.Id}",r);}catch(ArgumentException ex){return Results.BadRequest(new{code="VALIDATION_ERROR",message=ex.Message});}}); api.MapGet("/services",async(ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>Results.Ok(await service.ListServicesAsync(GroupId(user),ct)));
api.MapGet("/appointments/availability",async(Guid professionalUserId,DateTimeOffset startsAt,DateTimeOffset endsAt,ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>{if(!CanAccessProfessional(user,professionalUserId))return Results.Forbid();try{return Results.Ok(await service.CheckAvailabilityAsync(GroupId(user),professionalUserId,startsAt,endsAt,ct));}catch(ArgumentException ex){return Results.BadRequest(new{code="VALIDATION_ERROR",message=ex.Message});}});
api.MapPost("/appointments",async(CreateAppointmentRequest request,ClaimsPrincipal user,AgendaService service,IConfiguration config,CancellationToken ct)=>{if(!CanAccessProfessional(user,request.ProfessionalUserId))return Results.Forbid();if(request.ForceConflict&&!await CanForceConflictAsync(user,config,ct))return Results.Forbid();try{var secured=request with{GroupId=GroupId(user),CreatedByUserId=UserId(user)};var r=await service.CreateAppointmentAsync(secured,ct);return Results.Created($"/api/v1/appointments/{r.Id}",r);}catch(InvalidOperationException ex)when(ex.Message=="APPOINTMENT_CONFLICT"){return Results.Conflict(new{code="APPOINTMENT_CONFLICT",message="Já existe atendimento do profissional nesse intervalo."});}catch(ArgumentException ex){return Results.BadRequest(new{code="VALIDATION_ERROR",message=ex.Message});}});
api.MapGet("/appointments",async(Guid professionalUserId,DateTimeOffset from,DateTimeOffset to,ClaimsPrincipal user,AgendaService service,CancellationToken ct)=>{if(!CanAccessProfessional(user,professionalUserId))return Results.Forbid();return Results.Ok(await service.ListAppointmentsAsync(GroupId(user),professionalUserId,from,to,ct));});
app.MapHealthChecks("/health"); app.Run();
static Guid GroupId(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("group_id")??throw new UnauthorizedAccessException("Missing group claim.")); static Guid UserId(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue(ClaimTypes.NameIdentifier)??u.FindFirstValue("sub")??throw new UnauthorizedAccessException("Missing user claim.")); static bool IsAdmin(ClaimsPrincipal u)=>string.Equals(u.FindFirstValue("profile"),"ADMIN",StringComparison.OrdinalIgnoreCase); static bool CanAccessProfessional(ClaimsPrincipal u,Guid p)=>IsAdmin(u)||UserId(u)==p;
static async Task<bool> CanForceConflictAsync(ClaimsPrincipal user,IConfiguration config,CancellationToken ct){if(IsAdmin(user))return true;var cs=config.GetConnectionString("Postgres")??Environment.GetEnvironmentVariable("BCK_POSTGRES_CONNECTION")??throw new InvalidOperationException("PostgreSQL connection is not configured.");await using var c=new NpgsqlConnection(cs);await c.OpenAsync(ct);await using var cmd=new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM user_permission up JOIN permission p ON p.id=up.permission_id JOIN bck_user u ON u.id=up.user_id WHERE up.user_id=$1 AND u.group_id=$2 AND u.active=true AND up.granted=true AND p.code='ALLOW_FIT_IN')",c);cmd.Parameters.AddWithValue(UserId(user));cmd.Parameters.AddWithValue(GroupId(user));return (bool)(await cmd.ExecuteScalarAsync(ct))!;}
public partial class Program{}
