import 'package:flutter/material.dart';
import '../../core/api/bck_api_client.dart';
import '../../core/auth/session_store.dart';

class RescheduleAppointmentPage extends StatefulWidget {
  const RescheduleAppointmentPage({super.key, required this.session, required this.apiClient, required this.appointment, required this.professionalUserId});
  final StoredSession session; final BckApiClient apiClient; final AppointmentItem appointment; final String professionalUserId;
  @override State<RescheduleAppointmentPage> createState()=>_RescheduleAppointmentPageState();
}
class _RescheduleAppointmentPageState extends State<RescheduleAppointmentPage>{
  late DateTime _day; late TimeOfDay _time; late int _duration; late String _professionalId; Future<List<ManagedUserItem>>? _professionals; final _reason=TextEditingController(); bool _saving=false;
  bool get _isAdmin=>widget.session.profile.toUpperCase()=='ADMIN'||widget.session.isOwner;
  @override void initState(){super.initState();final s=widget.appointment.startsAt.toLocal();_day=DateTime(s.year,s.month,s.day);_time=TimeOfDay.fromDateTime(s);_duration=widget.appointment.endsAt.difference(widget.appointment.startsAt).inMinutes;_professionalId=widget.professionalUserId;if(_isAdmin)_professionals=widget.apiClient.professionals();}
  @override void dispose(){_reason.dispose();super.dispose();}
  DateTime get _start=>DateTime(_day.year,_day.month,_day.day,_time.hour,_time.minute);
  Future<void> _pickDay()async{final original=widget.appointment.startsAt.toLocal();final originalDay=DateTime(original.year,original.month,original.day);final today=DateTime.now();final todayDay=DateTime(today.year,today.month,today.day);final firstDate=originalDay.isBefore(todayDay)?originalDay:todayDay;final d=await showDatePicker(context:context,initialDate:_day,firstDate:firstDate,lastDate:DateTime(2100));if(d!=null)setState(()=>_day=d);}
  Future<void> _pickTime()async{final t=await showTimePicker(context:context,initialTime:_time);if(t!=null)setState(()=>_time=t);}
  Future<bool> _canFitIn()async{if(_isAdmin)return true;if(_professionalId!=widget.session.userId)return false;try{final me=await widget.apiClient.me(),raw=me['permissions'];return raw is List&&raw.map((e)=>e.toString().toUpperCase()).contains('ALLOW_FIT_IN');}catch(_){return false;}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Remarcar atendimento')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text(widget.appointment.clientName,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:20),if(_isAdmin)FutureBuilder<List<ManagedUserItem>>(future:_professionals,builder:(context,s)=>DropdownButtonFormField<String>(initialValue:_professionalId,decoration:const InputDecoration(labelText:'Profissional',prefixIcon:Icon(Icons.badge_outlined)),items:(s.data??[]).map((p)=>DropdownMenuItem(value:p.id,child:Text(p.name))).toList(),onChanged:(v){if(v!=null)setState(()=>_professionalId=v);})),if(_isAdmin)const SizedBox(height:16),ListTile(contentPadding:EdgeInsets.zero,onTap:_pickDay,leading:const Icon(Icons.calendar_month_rounded),title:Text('${_day.day.toString().padLeft(2,'0')}/${_day.month.toString().padLeft(2,'0')}/${_day.year}'),subtitle:const Text('Nova data')),ListTile(contentPadding:EdgeInsets.zero,onTap:_pickTime,leading:const Icon(Icons.schedule_rounded),title:Text('${_time.hour.toString().padLeft(2,'0')}:${_time.minute.toString().padLeft(2,'0')}'),subtitle:Text('Novo horário • $_duration min')),Wrap(spacing:8,children:[20,30,40,60,90,120].map((m)=>ChoiceChip(label:Text('$m min'),selected:_duration==m,onSelected:(_)=>setState(()=>_duration=m))).toList()),const SizedBox(height:20),TextField(controller:_reason,maxLines:3,decoration:const InputDecoration(labelText:'Motivo da remarcação',prefixIcon:Icon(Icons.notes_rounded),alignLabelWithHint:true)),const SizedBox(height:24),FilledButton.icon(onPressed:_saving?null:_save,icon:_saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.event_repeat_rounded),label:const Padding(padding:EdgeInsets.symmetric(vertical:14),child:Text('Confirmar remarcação')))])));
  Future<void> _save()async{setState(()=>_saving=true);try{final end=_start.add(Duration(minutes:_duration));final av=await widget.apiClient.appointmentAvailability(professionalUserId:_professionalId,startsAt:_start,endsAt:end);var force=false;final conflicts=av.conflicts.where((a)=>a.id!=widget.appointment.id).toList();if(conflicts.isNotEmpty){final allowed=await _canFitIn();if(!mounted)return;if(!allowed){await _blocked(conflicts);return;}force=await _confirm(conflicts);if(!force)return;}await widget.apiClient.rescheduleAppointment(widget.appointment.id,professionalUserId:_professionalId,startsAt:_start,durationMinutes:_duration,reason:_reason.text.trim().isEmpty?null:_reason.text.trim(),forceConflict:force);if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Não foi possível remarcar: $e')));}finally{if(mounted)setState(()=>_saving=false);}}
  String _conflicts(List<AppointmentItem>x)=>x.map((a){final s=a.startsAt.toLocal(),e=a.endsAt.toLocal();String hm(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';return '• ${a.clientName}: ${hm(s)}–${hm(e)}';}).join('\n');
  Future<void> _blocked(List<AppointmentItem>x)=>showDialog<void>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.block_rounded),title:const Text('Novo horário indisponível'),content:Text('${_conflicts(x)}\n\nEscolha outro horário.'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Voltar'))]));
  Future<bool> _confirm(List<AppointmentItem>x)async=>(await showDialog<bool>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.warning_amber_rounded),title:const Text('Remarcar como encaixe?'),content:Text('${_conflicts(x)}\n\nO novo horário ficará sobreposto e será identificado como encaixe.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Confirmar encaixe'))])))??false;
}
